import scrapy

class items2019(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE=scrapy.Field()
    LAST_RANK=scrapy.Field()
    FIRST_SCORE=scrapy.Field()
    FIRST_RANK=scrapy.Field()


class items2020(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE=scrapy.Field()
    LAST_RANK=scrapy.Field()
    FIRST_SCORE=scrapy.Field()
    FIRST_RANK=scrapy.Field()

class items2021(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE=scrapy.Field()
    LAST_RANK=scrapy.Field()
    FIRST_SCORE=scrapy.Field()
    FIRST_RANK=scrapy.Field()

class items2022(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE=scrapy.Field()
    LAST_RANK=scrapy.Field()
    FIRST_SCORE=scrapy.Field()
    FIRST_RANK=scrapy.Field()

class items2023(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE=scrapy.Field()
    LAST_RANK=scrapy.Field()
    FIRST_SCORE=scrapy.Field()
    FIRST_RANK=scrapy.Field()

class items2024(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE=scrapy.Field()
    LAST_RANK=scrapy.Field()
    FIRST_SCORE=scrapy.Field()
    FIRST_RANK=scrapy.Field()



class onitems2019(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE_12=scrapy.Field()
    LAST_RANK_12=scrapy.Field()
    LAST_SCORE_18=scrapy.Field()
    LAST_RANK_18=scrapy.Field()


class onitems2020(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE_12=scrapy.Field()
    LAST_RANK_12=scrapy.Field()
    LAST_SCORE_18=scrapy.Field()
    LAST_RANK_18=scrapy.Field()



class onitems2021(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE_12=scrapy.Field()
    LAST_RANK_12=scrapy.Field()
    LAST_SCORE_18=scrapy.Field()
    LAST_RANK_18=scrapy.Field()



class onitems2022(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE_12=scrapy.Field()
    LAST_RANK_12=scrapy.Field()
    LAST_SCORE_18=scrapy.Field()
    LAST_RANK_18=scrapy.Field()



class onitems2023(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE_12=scrapy.Field()
    LAST_RANK_12=scrapy.Field()
    LAST_SCORE_18=scrapy.Field()
    LAST_RANK_18=scrapy.Field()



class onitems2024(scrapy.Item):

    DEPARTMENT_NAME=scrapy.Field()
    DEPARTMENT_ID=scrapy.Field()
    UNIVERSITY_TYPE=scrapy.Field()
    UNIVERSITY_NAME=scrapy.Field()
    UNIVERSITY_ID=scrapy.Field()
    FACULTY_NAME=scrapy.Field()
    SCORE_TYPE=scrapy.Field()
    SCHOLARSHIP_TYPE=scrapy.Field()
    GENERAL_CAPACITY=scrapy.Field()
    SCHOOL_CAPACITY=scrapy.Field()
    GENERAL_ENROLLMENT=scrapy.Field()
    SCHOOL_ENROLLMENT=scrapy.Field()
    SUM_CAPACITY=scrapy.Field()
    SUM_ENROLLMENT=scrapy.Field()
    FIELD_RATE=scrapy.Field()
    LAST_SCORE_12=scrapy.Field()
    LAST_RANK_12=scrapy.Field()
    LAST_SCORE_18=scrapy.Field()
    LAST_RANK_18=scrapy.Field()